# Generated by Django 5.2.6 on 2026-06-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_accent',
            field=models.CharField(default='#10b981', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_bg',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_primary',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_surface',
            field=models.CharField(default='#1e293b', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_text',
            field=models.CharField(default='#f8fafc', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी (Hindi)'), ('bn', 'বাংলা (Bengali)'), ('te', 'తెలుగు (Telugu)'), ('mr', 'मराठी (Marathi)'), ('ta', 'தமிழ் (Tamil)'), ('gu', 'ગુજરાતી (Gujarati)'), ('kn', 'ಕನ್ನಡ (Kannada)'), ('ml', 'മലയാളം (Malayalam)'), ('pa', 'ਪੰਜਾਬੀ (Punjabi)'), ('or', 'ଓଡ଼ିଆ (Odia)'), ('es', 'Español (Spanish)'), ('fr', 'Français (French)'), ('de', 'Deutsch (German)'), ('ja', '日本語 (Japanese)'), ('zh', '中文 (Chinese)'), ('ar', 'العربية (Arabic)'), ('pt', 'Português (Portuguese)'), ('ru', 'Русский (Russian)'), ('ko', '한국어 (Korean)'), ('it', 'Italiano (Italian)')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('custom', 'Custom')], default='light', max_length=10),
        ),
    ]
