# Generated by Django 5.2.6 on 2026-06-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_profile_custom_accent_profile_custom_bg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.CharField(blank=True, max_length=500)),
                ('fetch_ok', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rate Cache',
                'verbose_name_plural': 'Rate Caches',
            },
        ),
    ]
